version: '3.7'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    command: ["npm", "start"]
    volumes:
      - './client:/app'
      - 'client-node-modules:/app/node_modules'
    ports:
      - 3001:3000
    stdin_open: true

volumes:
  client-node-modules: